AWSTemplateFormatVersion: "2010-09-09"
Description: Plantilla de ejemplo para stacks anidados

Parameters:
  pStage:
    Type: String
    Default: dev
    Description: Ambiente

Resources:
  rStackFinanceBackend:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL:
        Fn::Sub:
          - "https://s3.amazonaws.com/${s3BucketName}/cf/finance-backend.yaml"
          - s3BucketName:
              Fn::ImportValue: !Sub "${pStage}-deployment-finance-s3-name"
      Parameters:
        pStage: !Ref pStage
        DeploymentBucketName:
          Fn::ImportValue: !Sub "${pStage}-deployment-finance-s3-name"
        DeploymentBucketARN:
          Fn::ImportValue: !Sub "${pStage}-deployment-finance-s3-arn"
      Tags:
        - Key: Environment
          Value: !Ref pStage
        - Key: Application
          Value: CashiApp
