name: CI/CD to AWS AppRunner with GitHub Actions
on:
  push:
    branches: [development] # Trigger workflow on git push to main branch
  workflow_dispatch: # Allow manual invocation of the workflow

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Configure AWS credentials
        id: aws-credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Creating bucket for deployment
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: finance-deployment-stack
          template: cf/deployment.yaml
          capabilities: CAPABILITY_NAMED_IAM

      - name: Upload contents of 'cf' folder to S3 bucket
        run: |
          aws s3 sync cf s3://dev-deployment-finance-template-bucket/cf
          echo "Archivos subidos exitosamente"
          aws s3 sync api-rest s3://dev-deployment-finance-template-bucket/api-rest
          echo "Archivos subidos exitosamente"
        continue-on-error: true # Esto permite que el flujo continúe incluso si algún comando falla


      - name: Deploy to AWS CloudFormation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: finance-backend-stack-backend
          template: cf/main-finance.yaml
          capabilities: CAPABILITY_NAMED_IAM
          # parameter-overrides: "MyParam1=myValue,MyParam2=${{ secrets.MY_SECRET_VALUE }}"
